services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - MONGO_URL=mongodb://mongo:27017/taskhub
    depends_on:
      - mongo
volumes:
  mongo_data:
